config/routes.rb
Rails.application.routes.draw do
  root to: 'users/sessions#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :image_post
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image_post.rb
class ImagePost < ApplicationRecord
	mount_uploader :picture, PictureUploader
	validates :title , presence: true
	validate :picture_size
	private
	# Validates the size of an uploaded picture.
	def picture_size
		if picture.size > 5.megabytes
		errors.add(:picture, "should be less than 5MB")
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
  has_many :image_posts       
 # has_many :comments, dependent: :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
  	if user_signed_in?
  		redirect_to 'users/sessions'
  	else 
  		redirect_to 'image_posts/show'	
  	end 
  end 
end

app/controllers/image_posts_controller.rb
class ImagePostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_image_post, only: [:show, :edit, :update, :destroy]

  # GET /image_posts
  # GET /image_posts.json
  def index
    @image_posts = ImagePost.all
  end

  # GET /image_posts/1
  # GET /image_posts/1.json
  def show
  end

  # GET /image_posts/new
  def new
    @image_post = ImagePost.new
  end

  # GET /image_posts/1/edit
  def edit
  end

  # POST /image_posts
  # POST /image_posts.json
  def create
    @image_post = ImagePost.new(image_post_params)

    respond_to do |format|
      if @image_post.save
        format.html { redirect_to @image_post, notice: 'Image post was successfully created.' }
        format.json { render :show, status: :created, location: @image_post }
      else
        format.html { render :new }
        format.json { render json: @image_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_posts/1
  # PATCH/PUT /image_posts/1.json
  def update
    respond_to do |format|
      if @image_post.update(image_post_params)
        format.html { redirect_to @image_post, notice: 'Image post was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_post }
      else
        format.html { render :edit }
        format.json { render json: @image_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_posts/1
  # DELETE /image_posts/1.json
  def destroy
    @image_post.destroy
    respond_to do |format|
      format.html { redirect_to image_posts_url, notice: 'Image post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_post
      @image_post = ImagePost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_post_params
      params.require(:image_post).permit(:title, :picture)
    end
end

app/controllers/registrations_controller.rb
class RegistrationController <Devise :: RegistrationController>
	private 
	def sign_up_params
		params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
	end
	def account_update_params
     	params.require(:user).permit(:user_name, :email, :password, :password_confirmation, :current_password)
	end
		
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/image_posts_helper.rb
module ImagePostsHelper
end

app/views/image_posts/_form.html.erb
<%= form_for(@image_post, html: { multipart: true }) do |f| %>
  <% if image_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image_post.errors.count, "error") %> prohibited this image_post from being saved:</h2>

      <ul>
      <% image_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <span class="picture">
  <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script type="text/javascript">
$('#micropost_picture').bind('change', function() {
size_in_megabytes = this.files[0].size/1024/1024;
if (size_in_megabytes > 5) {
alert('Maximum file size is 5MB. Please choose a smaller file.');
}
});
</script>

app/views/image_posts/edit.html.erb
<h1>Editing Image Post</h1>

<%= render 'form', image_post: @image_post %>

<%= link_to 'Show', @image_post %> |
<%= link_to 'Back', image_posts_path %>

app/views/image_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Image Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @image_posts.each do |image_post| %>
      <tr>
        <td><%= image_post.title %></td>
        <td><%= image_tag image_post.picture.url if image_post.picture? %></td>
        <td><%= link_to 'Show', image_post %></td>
        <td><%= link_to 'Edit', edit_image_post_path(image_post) %></td>
        <td><%= link_to 'Destroy', image_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image Post', new_image_post_path %>

app/views/image_posts/new.html.erb
<h1>New Image Post</h1>

<%= render 'form', image_post: @image_post %>

<%= link_to 'Back', image_posts_path %>

app/views/image_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @image_post.title %>
</p>
<p>
  <%=image_tag @image_post.picture.url  %>
</p>


<%= link_to 'Edit', edit_image_post_path(@image_post) %> |
<%= link_to 'Back', image_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

            <% if user_signed_in? %>
            <p>HELLO</p>
            <%= current_user.user_name %>
            <%= link_to "sign_out" ,destroy_user_session_path , :method => 'delete' %>\
            <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>